/**
 * Service Worker Registration
 *
 * Handles PWA service worker registration and update notifications.
 * The service worker is auto-generated by vite-plugin-pwa during build.
 */

import { registerSW } from 'virtual:pwa-register'

/**
 * Registers the service worker with auto-update behavior.
 * Shows a notification when new content is available.
 */
export function registerServiceWorker() {
  const updateSW = registerSW({
    onNeedRefresh() {
      if (confirm('Nova versao disponivel! Atualizar agora?')) {
        updateSW(true)
      }
    },
    onOfflineReady() {
      console.log('App pronto para funcionar offline!')
    },
    onRegistered(registration) {
      console.log('Service Worker registrado:', registration)

      // Check for updates every hour
      if (registration) {
        setInterval(() => {
          registration.update()
        }, 60 * 60 * 1000)
      }
    },
    onRegisterError(error) {
      console.error('Erro ao registrar Service Worker:', error)
    },
  })
}
